# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHeadlessbrowser():
  def setup_method(self):
    op = webdriver.ChromeOptions()
    op.add_argument('headless')
    self.driver = webdriver.Chrome(options=op)
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_headlessbrowser(self):
    self.driver.get("https://github.com/login")
    self.driver.set_window_size(1280, 672)
    element = self.driver.find_element(By.LINK_TEXT, "Career-Elective-MiniProject/Mini-Project")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.LINK_TEXT, "Career-Elective-MiniProject/Mini-Project").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "Career-Elective-MiniProject").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-3").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-caret:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".js-feature-preview-indicator-container > .Header-link").click()
    self.driver.find_element(By.NAME, "q").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#jump-to-suggestion-repository-583257085 > .no-underline")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.NAME, "q").send_keys("hpc")
    self.driver.find_element(By.CSS_SELECTOR, "#jump-to-suggestion-repository-559160569 .jump-to-suggestion-name").click()
    self.driver.find_element(By.CSS_SELECTOR, ".BorderGrid-row:nth-child(2) > .BorderGrid-cell").click()

if __name__ == "__main__":
    test1=TestHeadlessbrowser()
    test1.setup_method()
    test1.test_headlessbrowser()
    test1.teardown_method()
