# Generated by Selenium IDE

import time
import json
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMemoryLoad():
  def setup_method(self):
    self.driver = webdriver.Chrome(service=Service('/usr/local/bin/chromedriver'))
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_memoryLoad(self):
    usr="xxx"
    pw="yyy"
    url1="http://10.0.xx.xx:3000/login"
    url2="http://10.0.xx.xx:3000/d/rYdddlPW/node-exporter-f?orgId=1&editPanel=78&from=1677038764147&to=1677125164181"
    self.driver.get(url1)
    self.driver.set_window_size(1292, 638)
    self.driver.find_element(By.NAME, "user").send_keys(usr)
    self.driver.find_element(By.ID, "current-password").click()
    self.driver.find_element(By.ID, "current-password").send_keys(pw)
    self.driver.find_element(By.ID, "current-password").send_keys(Keys.ENTER)
    time.sleep(8)
    self.driver.get(url2)
    time.sleep(8)
    self.driver.get("http://10.0.2.15:3000/d/rYdddlPW/node-exporter-f?orgId=1&editPanel=78&inspect=78")
    time.sleep(8)
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-obkt16-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-obkt16-button > .css-1mhnkuh")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".css-obkt16-button > .css-1mhnkuh").click()
    time.sleep(5)
if __name__ == "__main__":
  test1 = TestMemoryLoad()
  test1.setup_method()
  test1.test_memoryLoad()
  test1.teardown_method() 
 
